$content = [System.IO.File]::ReadAllText('Controllers\DonDatHangController.cs', [System.Text.Encoding]::UTF8)

$content = $content -replace '(?s)private SelectList GetTrangThaiList\(int\? selectedId = null\).*?return new SelectList\(items, "ID", "Name", selectedId\);\s*}', "private SelectList GetTrangThaiList(int? selectedId = null)`r`n        {`r`n            var items = _repo.GetTrangThaiList().Select(x => new DropdownItem { ID = x.ID, Name = x.TenTrangThai }).ToList();`r`n            return new SelectList(items, `"ID`", `"Name`", selectedId);`r`n        }"

$content = $content -replace 'TrangThaiDon = \(int\)TrangThaiDonHang\.ChuaGiao,', 'TrangThaiDon = 1,'

$content = $content -replace '(?s)public ActionResult CancelOrder\(int id\).*?return Json\(new \{ success = false, message = ".*?" \}\);\s*}', "public ActionResult UpdateStatus(int id, int trangThaiMoi)`r`n        {`r`n            var oldDon = _repo.GetById(id);`r`n            if (oldDon == null) return Json(new { success = false, message = `"Không tìm thấy đơn hàng.`" });`r`n            if (oldDon.TrangThaiDon == 3) return Json(new { success = false, message = `"Không thể chuyển trạng thái đơn hàng đã giao.`" });`r`n            if (oldDon.TrangThaiDon == 4) return Json(new { success = false, message = `"Đơn hàng này đã bị hủy trước đó.`" });`r`n`r`n            var session = GetCurrentUser();`r`n            int userId = session?.IDNhanSu ?? 0;`r`n`r`n            bool result = _repo.UpdateStatus(id, trangThaiMoi, userId);`r`n            if (result)`r`n            {`r`n                var newDon = _repo.GetById(id);`r`n                AuditLog.AddUpdate(`"NS_DonDatHang`", id.ToString(), oldDon, newDon);`r`n                AuditLog.SaveAudit(userId, `"Đơn đặt hàng`", `"DonDatHangController`", `"UpdateStatus`");`r`n                return Json(new { success = true, message = `"Chuyển trạng thái đơn hàng thành công.`" });`r`n            }`r`n            return Json(new { success = false, message = `"Lỗi khi chuyển trạng thái đơn hàng.`" });`r`n        }"

[System.IO.File]::WriteAllText('Controllers\DonDatHangController.cs', $content, [System.Text.Encoding]::UTF8)
